# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6823013c2c9b0bfc23d3d1248f7c6e96503e722d64c566d21a462256afccad8d5d48683aec77f50f514e410ce7bed8163d21d3395194f5fa2cb4b8cb82b3053b

test:
  secret_key_base: 0649f29390fa77288d8454167fc8bc8df0bac4b82bec506d8234deac8b69d9009240aec6ab33d4a07d9b30f9ead219239c9fa11d1e35519b7b5799851fabe480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
