# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04833c04d77bf5ebbe962515a953191d84a2f04d1dfd74e4b3dd3df74ed2f968d4ee6170ad2984ca06401438350c1e1125e8d4f3823cb10dfe312230580a33b1

test:
  secret_key_base: b7e8ccce214251046990edd9ce1b7479c8dbc4504b26183272c8c2ba5fa29120072088216019d2ad6a174907ab1967a7804cd148888b43fcc1716ec8836979af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
