# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 886f470afca302696f9e9b541efe6c0711080c397a067f159cb5fd095b145da28ab3578f0121f1da0e8c7b4964aa17a28e98e1bb3a26c1bf011c09581846a21c

test:
  secret_key_base: 670a78777bd3c329f0fcf21fa01f3bc16b7b9a06f5fb1eb37a98404ca1fb789abdcecc246790978ea366e99745a61324cb3285dabc795877c269e806472ab9e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
